version: '3.4'

networks:
  frontend:

services:
  mudblazorapp.server:
  container_name: mudblazor-wasm
    image: ${DOCKER_REGISTRY-}mudblazorappserver
    build:
      context: .
      dockerfile: Server/Dockerfile
    ports:
      - 7000:80
    networks:
      - frontend
    restart: on-failure